### ISSUE TITLE
Submit to official Pelican plugins repository

### ISSUE THREAD

**Issue by logological** [pR0Ps/pelican-yaml-metadata#2]
Would you consider submitting this plugin to the [official (new) Pelican plugins repository](https://github.com/pelican-plugins)?  The old repository contains [a plugin with similar functionality](https://github.com/joachimneu/pelican-md-metayaml) but it's broken and apparently no longer maintained.  Since this plugin does everything that one does, with the advantage of actually working with recent versions of Pelican, having it in the official repository would make it more discoverable.

**Comment by pR0Ps** [comment]
In progress: https://github.com/getpelican/pelican-plugins/issues/1340

**Comment by pR0Ps** [comment]
Done: https://github.com/pelican-plugins/yaml-metadata

Released on PyPI as [`pelican-yaml-metadata`](https://pypi.org/project/pelican-yaml-metadata/)
