### ISSUE TITLE
Specification of dependencies is perhaps too cautious

### ISSUE THREAD

**Issue by logological** [pR0Ps/pelican-yaml-metadata#3]
The `requirements.txt` file indicates that specific versions of the Markdown and PyYAML libraries (2.6.8 and 3.12, respectively) are required, though everything seems to work fine for me with Markdown 3.3.4 and PyYAML 5.4.1.  Was tying pelican-yaml-metadata to specific versions of Markdown and PyYAML a deliberate choice, or was this perhaps overly conservative?  If the latter, changing the requirements to `Markdown>=2.6.8` and `PyYAML>=3.12` might help avoid dependency conflicts with other plugins.

**Comment by pR0Ps** [comment]
Yeah, I made this a long time ago when I didn't know any better. And since it's still working fine I just haven't needed to touch it.

I'll go over it and modernize it at some point soon (and probably action #2 too)

**Comment by logological** [comment]
Thanks. If you're going to modernize everything, you might also consider checking out the [FarmCodeGary/pelican-yaml-metadata](https://github.com/FarmCodeGary/pelican-yaml-metadata) fork, which claims to have [fixed a bug relating to the reading of booleans](https://github.com/FarmCodeGary/pelican-yaml-metadata/commit/b26634656ef33197e27ff1eb4e13733cc97647c8).

**Comment by pR0Ps** [comment]
Just finished updating the deps and modernizing it, it should just be a matter of installing and enabling now.
